### ISSUE TITLE
Question about authentication process

### ISSUE THREAD

**Issue by michuer** [bcgov/did-auth-extension#2]
Hi, I try to use this add-on with Hyperlegder Indy demo.
Unfortunately, I'm not sure I fully understand how it works. Do I have to send a private key (signatureValue) to a relying party to confirm that I own a DID?
As I see in this add-on, signatureValue is predefined, it means that we have to take it out of the indy wallet ?

**Comment by swcurran** [comment]
No you don't send a private key. You send a piece of information that is signed by the private key that the other party that is holding the corresponding public key can confirm.

This document (PDF or MD links) should give you what you need to understand the verification being done: [https://github.com/WebOfTrustInfo/rwot6-santabarbara/blob/master/draft-documents/did_auth_draft.md](https://github.com/WebOfTrustInfo/rwot6-santabarbara/blob/master/draft-documents/did_auth_draft.md)
